const TMDB='https://api.themoviedb.org/3',IMG='https://image.tmdb.org/t/p/w500',BACK='https://image.tmdb.org/t/p/original',KEY=new URLSearchParams(location.search).get('tmdb_key')||localStorage.tmdbKey;
const fallback=['Nebula Run','Distrito Sombrio','Sol de Titã','AniCore','Código Aurora','Noite Prisma','Rota Kairo','Lendas de Éter','Ponto Zero','Orbitais'].map((title,i)=>({id:i+1,title,name:title,media_type:i%2?'tv':'movie',release_date:`202${i%7}-0${i%9+1}-12`,first_air_date:`202${i%7}-02-02`,vote_average:9-i*.2,overview:'Metadados TMDB, lista unificada, player modular e extensões inspiradas no fluxo Aniyomi/Stremio.',certification:[10,12,14,16][i%4]}));
let state={tab:'home',items:fallback,query:'',saved:fallback.slice(0,5).map((x,i)=>({...x,favorite:i%2===0})),select:false,selected:[]};
const $=s=>document.querySelector(s), title=i=>i.title||i.name, year=i=>(i.release_date||i.first_air_date||'2026').slice(0,4), poster=i=>i.poster_path?IMG+i.poster_path:`https://placehold.co/320x480/15151d/f2f1ff?text=${encodeURIComponent(title(i))}`, backdrop=i=>i.backdrop_path?BACK+i.backdrop_path:`https://placehold.co/1200x1700/101018/ffffff?text=${encodeURIComponent(title(i))}`;
async function tmdb(path,params={}){if(!KEY)throw Error('sem chave'); const u=new URL(TMDB+path);u.search=new URLSearchParams({api_key:KEY,language:'pt-BR',region:'BR',...params}); const r=await fetch(u); if(!r.ok)throw Error('tmdb'); return r.json()}
Promise.all([tmdb('/trending/all/week'),tmdb('/movie/now_playing'),tmdb('/tv/top_rated'),tmdb('/discover/tv',{with_genres:16})]).then(r=>{state.items=r.flatMap(x=>x.results).filter(x=>x.poster_path||x.backdrop_path).slice(0,44);render()}).catch(()=>render());
function meta(i){return `<span><i class="ri-star-fill"></i> ${Number(i.vote_average||0).toFixed(1)} • ${year(i)} • ${i.media_type==='tv'?'Série':'Filme'} • ${i.certification||14}</span>`}
function search(compact=''){return `<div class="search ${compact}"><i class="${state.query?'ri-close-line':'ri-search-2-line'}" data-clear></i><input placeholder="Buscar filmes, séries e animes" value="${state.query}"></div>`}
function card(i,o={}){let watch=o.progress,remaining=`${18+i.id%42} min restantes`;return `<article class="card ${watch?'watching':''}" data-id="${i.id}">${o.rank?`<b class="rank">${o.rank}</b>`:''}<div class="poster"><img src="${watch?backdrop(i):poster(i)}">${watch?'':`<em><i class="ri-star-fill"></i>${Number(i.vote_average||0).toFixed(1)}</em><small>${i.certification||14}</small>`}${o.locked?'<strong><i class="ri-heart-fill"></i></strong>':''}${o.checked!==undefined?`<span class="check ${o.checked?'on':''}"><i class="${o.locked?'ri-lock-2-line':'ri-check-line'}"></i></span>`:''}${watch?`<b class="remaining">${remaining}</b><div class="bar"><span style="width:${35+i.id%50}%"></span></div>`:''}</div><h3>${title(i)}</h3></article>`}
function row(name,items,o={}){return `<section class="row"><h2>${name}</h2><div class="rail">${items.map((i,n)=>card(i,{...o,rank:o.top?n+1:null})).join('')}</div></section>`}
function home(items){let h=items[0]||state.items[0];return `<header class="top"><div class="brand"><i class="ri-movie-2-fill"></i><b>CineFlux</b></div>${search('compact')}<button class="avatar"><i class="ri-user-smile-line"></i></button></header>${state.query?results(items):`<div class="hero" style="background-image:linear-gradient(180deg,rgba(10,10,16,.1),#0b0b12 82%),url(${backdrop(h)})"><div class="heroContent"><p class="logoText">${title(h)}</p>${meta(h)}<button class="watch"><i class="ri-play-fill"></i> Assistir</button><div class="actions"><button data-save="${h.id}"><i class="ri-add-line"></i></button><button><i class="ri-heart-3-line"></i></button><button><i class="ri-share-forward-line"></i></button></div><div class="dots"><i></i><i></i><i></i><i></i><i></i></div></div></div>${row('Continuar Assistindo',items.slice(0,10),{progress:true})}${row('Lançamentos',items.slice(2,14))}${row('Top 10 Filmes',items.slice(0,10),{top:true})}${row('Top 10 Séries',items.slice(0,10),{top:true})}${row('Filmes',items.slice(5,17))}${row('Séries',items.slice(8,20))}${row('Animes',items.slice(10,22))}`}`}
function results(items){return `<div class="listResults">${items.map(i=>`<div class="result"><img src="${poster(i)}"><div><h3>${title(i)}</h3>${meta(i)}<p>${i.overview||'Pronto para receber URLs de vídeo por extensões JSON.'}</p></div></div>`).join('')}</div>`}
function explore(items){return `<section class="page">${search()}<div class="chips">${['Filmes','Séries','Animes','Gêneros','Ano','Nota mínima'].map((c,i)=>`<button>${c}${i>2?'<i class="ri-arrow-down-s-line"></i>':''}</button>`).join('')}</div><div class="grid">${items.slice(0,30).map(i=>card(i)).join('')}</div></section>`}
function library(){return `<section class="page"><div class="listTop">${search('compact')}<button data-select><i class="ri-delete-bin-6-line"></i></button></div><div class="grid">${state.saved.map(i=>card(i,{locked:i.favorite,checked:state.select?state.selected.includes(i.id):undefined})).join('')}</div>${state.select&&state.selected.length?'<button class="fab" data-remove>Excluir selecionados</button>':''}</section>`}
function settings(){return `<section class="page settings"><div class="settingsLogo"><i class="ri-movie-2-fill"></i><b>CineFlux</b></div>${[['Aparência','ri-palette-line','Tema, Material You e cards'],['Reprodutor','ri-play-circle-line','Player interno, gestos e legendas'],['Downloads','ri-download-cloud-2-line','Fila, Wi-Fi e arquivos salvos'],['Dados e armazenamento','ri-database-2-line','Google, Drive, cache e pasta local'],['Avançado','ri-tools-line','Extensões, permissões e logs'],['Sobre','ri-information-line','TMDB, GitHub e políticas']].map(g=>`<article class="setting"><i class="${g[1]}"></i><div><h3>${g[0]}</h3><p>${g[2]}</p></div><i class="ri-arrow-right-s-line"></i></article>`).join('')}<p class="tmdb">Este produto usa a API do TMDB, mas não é endossado ou certificado pelo TMDB.</p></section>`}
function render(){let items=state.items.filter(i=>title(i).toLowerCase().includes(state.query.toLowerCase()));$('#app').innerHTML=(state.tab==='home'?home(items):state.tab==='explore'?explore(items):state.tab==='list'?library():settings())+`<nav class="bottom">${[['home','ri-home-5-line','Home'],['explore','ri-compass-3-line','Explorar'],['list','ri-bookmark-3-line','Sua lista'],['settings','ri-settings-4-line','Ajustes']].map(n=>`<button data-tab="${n[0]}" class="${state.tab===n[0]?'active':''}"><i class="${n[1]}"></i><span>${n[2]}</span></button>`).join('')}</nav>`; bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.query='';render()});document.querySelectorAll('.search input').forEach(i=>i.oninput=e=>{state.query=e.target.value;render()});document.querySelectorAll('[data-clear]').forEach(i=>i.onclick=()=>{state.query='';render()});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{let it=state.items.find(x=>x.id==b.dataset.save); if(it&&!state.saved.some(x=>x.id===it.id))state.saved.push(it);render()});let sel=$('[data-select]'); if(sel)sel.onclick=()=>{state.select=!state.select;state.selected=[];render()};document.querySelectorAll('.grid .card').forEach(c=>c.onclick=()=>{if(state.tab==='list'&&state.select){let it=state.saved.find(x=>x.id==c.dataset.id); if(it.favorite)return; state.selected=state.selected.includes(it.id)?state.selected.filter(x=>x!==it.id):[...state.selected,it.id];render()}});let rem=$('[data-remove]'); if(rem)rem.onclick=()=>{state.saved=state.saved.filter(i=>i.favorite||!state.selected.includes(i.id));state.selected=[];state.select=false;render()}}
render();
